location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_modules_msgs
    name: mrs_modules_msgs
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_modules_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial
    name: mrs_serial
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins
    name: mrs_rviz_plugins
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
